spring.application.name=finai-backend-espanol
spring.datasource.url=jdbc:postgresql://localhost:5432/tpgrupo2
spring.datasource.username=postgres
spring.datasource.password=221012
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never
server.error.include-stacktrace=never
server.port=8080
jwt.secret=0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==
